### ISSUE TITLE
Links on a proposal should be open on new tab

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#1050]

**Comment by AlanNabiev** [comment]
I can work on this

**Comment by AlanNabiev** [comment]
@bonustrack done in #1067

**Comment by ChaituVR** [comment]
@AlanNabiev This Issue is meant to be for links on a proposal

For example if you go to here:
https://snapshot.org/#/dydxgov.eth/proposal/0x3d62d5b77b2b9bd3ab1c42c296cc36ccf89f77bea22815081e785d5d28d32366
![image](https://user-images.githubusercontent.com/15967809/142391470-809c56ec-e7ce-4594-b991-4b4e23c92856.png)
clicking on link above should open a new tab

**Comment by AlanNabiev** [comment]
Sorry I misunderstood. I'll fix it now

**Comment by AlanNabiev** [comment]
@ChaituVR fixed in #1073
