### ISSUE TITLE
Cannot join a team with Trezor 

### ISSUE THREAD

**Issue by kargakis** [snapshot-labs/snapshot#1184]
Although I have logged in with the `Trezor (with MetaMask)` option which enables signing untyped data so voting with Trezor works, `Join`ing a team still triggers signing typed data so currently if I use Trezor I cannot join a team.

**Comment by samuveth** [comment]
This is because Trezor isn't supporting EIP712. You can follow progress on this here https://github.com/snapshot-labs/snapshot/issues/950

**Comment by kargakis** [comment]
@samuveth I am aware Trezor does not support EIP712 (https://github.com/trezor/trezor-firmware/issues/131#issuecomment-981817990), I was thinking that since you already support signing untyped data for voting that you could also update Join to trigger signing untyped data.

**Comment by samuveth** [comment]
> I was thinking that since you already support signing untyped data for voting that you could also update Join to trigger signing untyped data, until Trezor fully supports EIP712 which is at least a couple of months out.

The Model T and Model One EIP712 integration is progressing very fast and multiple PR's have already been merged. You can follow the latest progress here https://github.com/MetaMask/metamask-extension/issues/11498#issuecomment-1002628501

Sorry for any inconveniences this may cause, but we want to focus our resources on moving forward rather than backwards.
