### ISSUE TITLE
We should use Rinkeby as default network for demo.snapshot.org

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#1197]
This is to avoid cost for testing space creation

**Comment by ChaituVR** [comment]
Maybe better to create a new app? rinkeby.snapshot.org?

**Comment by samuveth** [comment]
> Maybe better to create a new app? rinkeby.snapshot.org?

I think this is a good idea because we might want to support ENS on multiple other networks in the future. This will help us keep things separated.

**Comment by bonustrack** [comment]
Its unlikely that we would support many network, each network require his own setup and snapshot-hub instance

**Comment by bonustrack** [comment]
What's blocking here:

- Need a way to handle IPNS url for multiple networks
- Figure out what we do with current data from demo

**Comment by mktcode** [comment]
> Its unlikely that we would support many network, each network require his own setup and snapshot-hub instance

Yea, one testnet should be enough, because we're coming from 0 anyway, so... 100% improvement. :)

I'm trying to see though the user's eyes as good as I can and I wonder whether it should really only be in the demo tbh. To be there it needs to be integrated anyway and then hidden on live page. But that's probably the exact moment when people start wondering about it and need to have the answer presented to them, ideally... When they are on snapshot.org and click on the plus sign on the left. "Hmmm... I need ENS... Can I test on testnet?" What I mean is.... either I'd actually have it enabled on the live site or there needs to be some hint for first-time visitors: "Look here! We have a demo. Try everything in a test environment with a Rinkeby domain."

![image](https://user-images.githubusercontent.com/6792578/147693908-f79042da-393f-4913-8c7d-04b83248436a.png)

Or an even more "in your face" message on the main page, but then really only for first time visitors, via flag in local storage. How is this demo currently promoted? Can't find any reference anywhere except discord messages.

Alternatively I could also think of the demo more as a feature of the live page instead of it's own instance, so to say, especially considering there's already a super cool playground for strategies.

![image](https://user-images.githubusercontent.com/6792578/147696268-ea49a790-b816-428a-8da1-c86eb0b1e304.png)

![image](https://user-images.githubusercontent.com/6792578/147695142-3c3d1a7c-a4a5-4b09-b99a-aa3def7daee8.png)
(The connected network doesn't really matter from our side but could of course be used as a user intention indicator, so to say.)

~~demo.snapshot.org could, in some distant future, be a public development staging instance.~~ 🙊

**Comment by mktcode** [comment]
![image](https://user-images.githubusercontent.com/6792578/148066547-96584f63-bd77-48de-8ddd-d33cd10834bc.png)
I see this box on the setup page now. That's where I would mention the demo too.

"Not sure how to create a space? Learn more in the documentation **, check out the demo** or join Snapshot Discord."

Maybe we should also make text links stand out a bit more.

**Comment by mktcode** [comment]
[For IPNS](https://github.com/snapshot-labs/snapshot/blob/24f1c01047fa3f9dee07f70b749f5fbd3959c673/src/views/SpaceSettings.vue#L74-L80)

Isn't this the only place that needs to be adjusted?
