### ISSUE TITLE
Page description 

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#1395]
We should add a page description, currently snapshot appears like this on google 
![image](https://user-images.githubusercontent.com/51686767/147935527-800c91bf-fd17-4362-81cb-602ba59968a2.png)

**Comment by sasicodes** [comment]
I'll work on this. Also if we have,
- set of keywords
- Open Graph images
- Sitemap

@samuveth

**Comment by bigint** [comment]
@samuveth @samuveth We kind of blocked by this 🤔 

https://github.com/snapshot-labs/snapshot/issues/1210

**Comment by cristijora** [comment]
Sort of new here, but my opinion on these SEO related issues is the following:

Adding page descriptions is more of a SEO workaround for the current project setup.
The project right now is setup as a SPA which means that everything you do around SEO will be by default not optimal for search engines. Although search engines can crawl SPA content it's often not as reliable as Server Side Rendered content.

Therefore a proper solution for this is to add SSR at least for some pages which would benefit from it. Some examples are:
- Main page (explore page)
- Spaces pages including about page for each space
- Proposal pages

**Technical implementation notes**
We could use [vite-ssg](https://github.com/antfu/vite-ssg)
We would have to change the url structure and remove the hash from the url `/#/`. In order to avoid breaking change we can implement a temporary redirect from all routes with `/#/something` to `/something`.
Lastly this could have an impact on certain code and the way the website is currently deployed.

Long term, having SSR would be way more beneficial for the project meaning that proposals & spaces are indexed by search engines and will appear in search results providing more website traffic.

**Comment by samuveth** [comment]
@cristijora Yes we have considered SSR, but we use Fleek to deploy/host our files on IPFS and they do not provide a server for SSR. I have been looking into JAMstack which would allow us to statically generate pages (spaces, proposals, strategies, ...) at build time and then upload them to IPFS. This might sound like we lose a lot of dynamic functionality but this doesn't seem to be the case.

These are some resources that I found:
- https://withblue.ink/2020/01/21/watch-javascript-apps-going-inter-planetary.html
- https://www.smashingmagazine.com/2020/07/differences-static-generated-sites-server-side-rendered-apps/
- https://hasura.io/blog/approaches-to-add-dynamic-content-statically-generated-sites-jamstack/
- https://www.smashingmagazine.com/2019/12/dynamic-async-functionality-jamsstack-websites/

Would love to hear your thoughts!

@sasicodes sorry didn't mean to delete your comment.

@bigint as a fix just for our homepage we can use something `vue-meta` I think.

**Comment by cristijora** [comment]
@samuveth You can statically generate pages but in my opinion that wouldn't really fully solve the issue.
Consider that now there are 4.44k spaces. Only generating pages for those spaces might take a bunch of time at build time and if you include proposals it goes trough the roof.

Indeed you don't lose any dynamic functionality but if you want to generate the pages at build time for all spaces/proposals it will be very hard to maintain as those numbers grow.

**Comment by samuveth** [comment]
@cristijora Hm, then I wonder how something like twitter handles this (I heard they switched to JAMstack). Another solution could be using our own server and as service like https://prerender.io/

**Comment by zzuziak** [comment]
Added a new pitch in the Project Roadmap that needs scoping :pray:

**Comment by samuveth** [comment]
To clarify, this issue was marked as closed due to the lack of a viable solution for maintaining SEO-friendly meta tags on the homepage without cluttering the space page.
