### ISSUE TITLE
Add a way to change plugins order from settings

### ISSUE THREAD

**Issue by metrox-eth** [snapshot-labs/snapshot#1984]
In some space plugin order doesn't make much sense, i.e. having quorum after I voted POAP. 
<img width="330" alt="Capture d’écran 2022-03-23 à 18 04 52" src="https://user-images.githubusercontent.com/55286013/159686035-418e2edf-5b8f-4a44-b203-4e87a015a95a.png">
We could let users reorder the plugins with drag and drop.
<img width="588" alt="Capture d’écran 2022-03-23 à 18 04 25" src="https://user-images.githubusercontent.com/55286013/159686047-9e48662d-7125-4861-8bca-df194d64df40.png">

**Comment by samuveth** [comment]
@mktcode @metrox-eth  in the case of the quorum plugin we should work on a way to remove it I think, quorum is already a core feature in the settings and will be shown inside the results block.

**Comment by samuveth** [comment]
@mktcode if this requires changes to UI would be best to start with wires. Not sure it's current worth it, as for quorum it's not need like I explained above.

**Comment by zzuziak** [comment]
Hey @samuveth, is this issue still relevant or can we close?

**Comment by mktcode** [comment]
Drag/drop ordering functionality could be added here:

![image](https://user-images.githubusercontent.com/6792578/217610729-5abd000b-68eb-481a-853d-626c32195bd9.png)

This could result in a new `_uiOrder` property (`_` for "internal") in the plugins' configs, added on save:

```javascript
"plugins": {
  "quorum": {
    "_uiOrder": 0,
    "total": 75000,
    // ...
  },
  "safeSnap": {
    "_uiOrder": "1",
    "safes": [],
    // ...
  }
}
```

This can then be used to order the plugins [here](https://github.com/snapshot-labs/snapshot/blob/53472750345dc269701602bd49f109ab272b771c/src/components/SpaceProposalPlugins.vue#L18) and [here](https://github.com/snapshot-labs/snapshot/blob/53472750345dc269701602bd49f109ab272b771c/src/components/SpaceProposalPluginsSidebar.vue#L24) and theeeen [this function](https://github.com/snapshot-labs/snapshot/blob/53472750345dc269701602bd49f109ab272b771c/src/composables/usePlugins.ts#L35-L56) needs some adjustment, to loop over the ordered keys instead of the imported components.

Maybe this mounting mechanic can be improved altogether. I wasn't super happy with it back then. Felt a bit cumbersome. Actually I started to question the whole plugin system a bit. First of all the term "plugin" has a quite specific meaning for me. A plugin is usually not part of the project's codebase. It just provides a common API that plugins can be developed for and then they need to be installed. Our plugins are (technically) just optional core functionality, implemented in a maybe too cumbersome way, depending on what the plugin system actually is supposed to be. I guess in the beginning a more "plugin-like" approach was planned but it ended up to be just PRs to our codebases. Maybe it's simpler to just treat them as such. In [the new Safesnap implementation](https://github.com/snapshot-labs/snapshot/tree/mkt/safesnap-refactoring/src/plugins/safeSnap) I already didn't even use the plugins directory for anything other than entry points. All the code lives in `composables` and `components`.

**Comment by samuveth** [comment]
@zzuziak not really, we can leave this for now. Would be interesting to have another look at it while we refactor/redesign the settings page. Added it to the milestone.
