### ISSUE TITLE
Boost

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#2110]
@mktcode Like we discussed before, I think this feature should be reevaluated through a pitch.

Otherwise, it would also be great to see some wires before things get implemented in the Ui.

**Comment by mktcode** [comment]
# Motivation

We want to allow spaces to reward users for voting, to increase participation. The POAP plugin does that with NFTs but those NFTs have no value, unless they are utilized in other applications and voting power is not a factor in this. Boost is meant to add a more direct, financial incentive to participate and hold DAO tokens.

# Problems

## Voter motivation

Members that hold larger amounts of tokens are intrinsically motivated to vote, simply because their opinion has more impact on the result. Members with smaller token amounts can be discouraged by that, feeling like their vote doesn't matter that much anyway. This is true on the individual level but of course not when many small votes add up to compete with whale votes.

### Solution

We could implement mechanics to favor smaller votes in the rewards distribution. A pinch of randomness could make it more exiting and not solely based on voting power.

## Rewards distribution

Distributing rewards can be costly and/or cumbersome. The voting data exists and is accessible but won't be used a lot and only in custom implementations and processes per DAO, which is not ideal for voters.

DAOs with a multisig-wallet, like gnosis safe, might prefer to fund the rewards from their safe. 

### Solution

A snapshot UI plugin can provide a generalized and trusted solution for all DAOs. Rewards can be deposited in a smart contract that releases them based on a merkle tree generated in the snapshot hub.

At the same time this contract can act as a gnosis safe module, allowing DAO owners to fund the rewards pool directly from their safe, but still through the snapshot UI.

# Implementation

to be continued...

**Comment by samuveth** [comment]
https://basecamp.com/shapeup/1.1-chapter-02#steps-to-shaping
https://basecamp.com/shapeup/1.5-chapter-06
https://basecamp.com/shapeup/1.5-chapter-06#examples

Would be great to follow the shaping process and if patches are all written in the same format.

**Comment by zzuziak** [comment]
Will be handled in separate repository.
