### ISSUE TITLE
Publishing flow

### ISSUE THREAD

**Issue by jnordberg** [snapshot-labs/snapshot#29]
<img width="811" alt="Screen Shot 2020-08-31 at 08 27 56" src="https://user-images.githubusercontent.com/95886/91671686-e71dc900-eb63-11ea-9d6c-a78198feef65.png">

First time users will have a hard time publishing a proposal without an instruction manual

 - What is the function of "snapshot block number" and how do you obtain it?
   - Does it have to be displayed to the user? If yes could it be automatically filled?
 - Error messages, currently the button is only grey with no explanation when something is missing.
   - I managed to get it into a state where I seemingly had everything correctly filled in but the button was still greyed out

**Comment by densmirnov** [comment]
_'snapshot block number'_ is the block number from which the participants' balances will be taken;

And it's possible that the button was greyed out because you didn't fill all the answer options (and, yes, this is frustrating, it's better to add a simple pop-up message with missing values when you hover inactive button)

**Comment by bonustrack** [comment]
@jnordberg Agree it's confusing, we may want to have a modal that open when you click on "Snapshot block number" where you can easy pickup the current block number or select a date in future / past and estimate the block number. But that's not so much of a priority i believe.
