### ISSUE TITLE
[BUG] - Can't vote with a safe on Optimism

### ISSUE THREAD

**Issue by metrox-eth** [snapshot-labs/snapshot#3108]
### Briefly describe the bug.

Unable to to vote from Optimism Safe

### How can we reproduce the bug?

1. Go to your OP Gnosis Safe
2. Cast a vote on an OP proposal
3. See error

### What is the expected behaviour?

I should be able to cast a vote from an OP safe

### Can you attach screenshots?

<img width="1438" alt="Capture d’écran 2022-09-08 à 20 31 32" src="https://user-images.githubusercontent.com/55286013/189136297-d997c518-67f0-4409-87d8-c51a0e769501.png">

### Can you provide your device specific details below?

1. Device Type - [ex. Desktop or Mobile]
2. Device OS - [ex. Android, MacOS, Windows, iOS]
3. OS Version - [ex. iOS 11, Windows 10]
4. Browser - [ex. chrome, safari]
5. Browser Version - [ex. 101]
6. Wallet - [metamask, portis, walletconnect]
7. Space - [ex. ENS, Gitcoin]
8. Any additional information we should know -

**Comment by samuveth** [comment]
@bonustrack is there any known issue with the relayer?

**Comment by RomanHiden** [comment]
we have the same issue here

**Comment by ChaituVR** [comment]
@RomanHiden Can you share with us the space and OP address you are trying to vote? also transactions if any 

Make sure the space you are voting is using OP too. you can't vote on a space that is using other networks.

**Comment by ChaituVR** [comment]
These are the problems that happened:
- Users were trying to vote with `ETH` safe on the `OP` network space, Now it is not possible to vote with a safe on a space with a different network, so if someone is delegating to you on `ETH` safe and your `OP` safe is on a different address, ask your delegators to delegate you again on `OP` safe address https://gov.optimism.io/t/voting-cycle-3-roundup/2923/33 

- In the above screenshot by @metrox-eth He was using `OP` safe but trying to vote on an `ETH` space - which won't work as well
- On the `OP` network, only `1.3.0` version safes are supported and safes created by factory `0xC22834581EbC8527d974F8a1c97E1bEA4EF910BC` are supported https://github.com/safe-global/safe-deployments/blob/main/src/assets/v1.3.0/proxy_factory.json#L11, so votes coming from any other safes are not counted
- Users were using wallet connect to vote (which was not working) because snapshot is not available as an app on safe's `OP` network, We created an issue for this here - https://github.com/5afe/safe-apps-list/issues/183
- Even if snapshot is not available as an app, users can still add it as a custom app and vote https://docs.snapshot.org/gnosis-safe
- We fixed the issues with wallet connect now at https://github.com/snapshot-labs/snapshot/commit/c0ad6197c7aa7d4ad5d24e41356c4071ee46fc61 so users should be able to vote with it too :) so voting from safe app or walletconnect, both should work 🚀
