### ISSUE TITLE
[NEW FEATURE] - Show error modal when making action with wrong timestamp

### ISSUE THREAD

**Issue by metrox-eth** [snapshot-labs/snapshot#3346]
### Briefly describe the feature.

Add error message upon joining space with wrong timestamp

### Which problem is this feature trying to solve?

It's a recurring support issue that users with unsynchronized device clock can't join spaces and there in no error for this atm.

### What is the expected solution?

Adding an appropriate error, possible better to show an error in layman terms like "Your computer time is not accurate" instead of Oops wrong timestamp that doesn't tell much to the average user. It would also help if the error not collapse after a couple of second and show a link to the relevant solution:
https://github.com/snapshot-labs/snapshot/discussions/769

### How do you currently handle this problem?

Currently it cause frustration to users and eventually a small part of them can solve it after unnecessary use of the support. Assuming for each user that solve the issue 10 may give up on Snapshot.

**Comment by samuveth** [comment]
@bonustrack why do we need the timestamp from the user end in the first place if we already have it and validate it on the hub?

**Comment by bonustrack** [comment]
@samuveth Can you reproduce the issue? Not sure how this would happen, we allow 3 days expired timestamp and on frontend we use current timestamp. We are adding the timestamp on the payload so we can track it in our API without relying on another source. If the timestamp were not on the message we would need to timestamp the messages ourself and create extra data than others who want to sync our data wouldn't have (if we imagine with a hub that anyone can run and sync the whole Snapshot data). And we dont replace timestamp for the same reason and also because we dont to alter the message and break signature verification.

**Comment by samuveth** [comment]
@bonustrack yes I can reproduce. On my mac I put the date back one month and then try to follow a space.
<img width="691" alt="image" src="https://user-images.githubusercontent.com/51686767/205009202-9591032d-570e-456b-805e-1a8d108578e7.png">

**Comment by zzuziak** [comment]
IMO this should be solved by displaying an informative error message, we shouldn't mess with manipulating the timestamps :pray:

**Comment by samuveth** [comment]
@zzuziak  Yes, then we need to solve this everywhere not just for joining a space. I'm thinking of a modal that pops up whenever a user tries to make an action with an invalid timestamp.
