### ISSUE TITLE
[BUG] - Proposal page and proposal creation page sending lot of requests to brovider

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#3362]
### Briefly describe the bug.

Proposal page and proposal creation page sending lot of requests to brovider

### How can we reproduce the bug?

1. Connect with wallet connect and Go to any proposal, or any space's proposal creation page
2. open network tab in console, see that many requests are being sent to brovider

### Proposal page:
![image](https://user-images.githubusercontent.com/15967809/204512622-9570747c-1f98-4269-9c7c-fc3bca2aea02.png)
### Proposal creation page:
![image](https://user-images.githubusercontent.com/15967809/204512647-c95c6c21-28e2-41cb-bbc8-d1a061634e60.png)

**Comment by samuveth** [comment]
This happens on any page not only space pages. The issue of repeated calling seems to be somewhere deep inside the walletconnect code and it is calling our rpc because we provide it [here](https://github.com/snapshot-labs/snapshot/blob/0b74d2052171b4ca8669c6728f4d3ef8feccfc7a/src/helpers/connectors.json#L11)

**Comment by samuveth** [comment]
I've created an issue on the WalletConnect repo
