### ISSUE TITLE
chore: replace linters with @snapshot-labs/eslint-config-vue and @snapshot-labs/prettier-config

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#3369]
We should move to our common rules for eslint and prettier with `@snapshot-labs/eslint-config-vue` and `@snapshot-labs/prettier-config`, see example
https://github.com/snapshot-labs/sx-ui/pull/344/files

**Comment by samuveth** [comment]
@bonustrack I can't find `@snapshot-labs/eslint-config-vue` package or repo anywhere. Can you link it I'd like to have a look at the config before adding it to the Ui

**Comment by ChaituVR** [comment]
@samuveth 
Packages:
https://www.npmjs.com/package/@snapshot-labs/eslint-config-vue
https://www.npmjs.com/package/@snapshot-labs/eslint-config-base
https://www.npmjs.com/package/@snapshot-labs/prettier-config
Repo:
https://github.com/snapshot-labs/config

**Comment by samuveth** [comment]
Doesn't work well because snapshot and sx are following a different design philosophy. f.e single name components. Also snapshot is quite big and has lots of additional config that it wouldn't want to add to the global config because it would bloat it.

I recommend we leave snapshot config how it is for now.
