### ISSUE TITLE
Add a retry button if shutter results are not calculated

### ISSUE THREAD

**Issue by ChaituVR** [snapshot-labs/snapshot#3555]
Similar to when a proposal is not able to calculate scores, we should have a way to retry scores/results calculated, 

To reproduce https://demo.snapshot.org/#/snapspace.eth/proposal/0x26d800123c75ed70e12d78118fb545a4cbe7d70eaf83f91ec57597e6cfe3e01f
Shutter won't work on demo, but will be helpfull to understand the case

**Comment by samuveth** [comment]
I don't see shutter on the proposal that you linked

**Comment by ChaituVR** [comment]
Opps, updated 👍 Also, the Proposal is just to show how it looks, but the shutter won't work on the demo

**Comment by samuveth** [comment]
Perfect thanks! 

Solution would be something like this:
- Add check for `proposal.state === 'closed' && scores_state === ''`
- If true, then in `SpaceProposalResultsError.vue` show reload button that calls  `https://hub.snapshot.org/api/scores/<PROPOSAL_ID>`

@j0hnfl0w Assigning you to this, let me know if anything is unclear

**Comment by samuveth** [comment]
@ChaituVR currently with the example proposal that you provided the scores_state is an empty string. Is this a bug, shouldn't it be "invalid" or "failed" if we fail to decrypt the choices?

**Comment by ChaituVR** [comment]
> Add check for proposal.state === 'closed' && proposal.scores_state === '' && proposal.privacy === 'shutter'

Actually I think we should check `pending` it should not be an empty string at all, will ask Fabien https://github.com/snapshot-labs/snapshot-sequencer/pull/25

**Comment by samuveth** [comment]
@ChaituVR any update on this?

**Comment by ChaituVR** [comment]
@samuveth the PR is merged, you can expect it to be `'pending'` 

Note: few old proposals with no votes should still have `''` but we can ignore this case for now.

**Comment by ChaituVR** [comment]
Yep, if `score_state` is `pending`

**Comment by Todmy** [comment]
Investigated it. We already have this functionality:

<img width="1048" alt="Screenshot_2023-05-12_at_10 13 23" src="https://github.com/snapshot-labs/snapshot/assets/7693369/563923ec-4f67-4b97-a5e5-c75ffae66cec">

It doesn't work for [this](https://demo.snapshot.org/#/snapspace.eth/proposal/0x26d800123c75ed70e12d78118fb545a4cbe7d70eaf83f91ec57597e6cfe3e01f) because here we get an empty string for `score_state` property. But as @ChaituVR said, it was fixed and now `score_state` should be `"pending"` for similar cases. If so, then we don't need any change here.
