### ISSUE TITLE
Clicking signature icon scrolls to top

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/snapshot#3743]
https://www.loom.com/share/54fd412bf905415eb9dc994e00c3ed0a

**Comment by j0hnfl0w** [comment]
Yeah it is because of focus prop in Popover from headless ui.

**Comment by wa0x6e** [comment]
I was already looking at it., bug was introduced when fixing the keyboard navigation.

It is indeed from `focus` prop, but it does not have that bug on headless ui demo, still trying to figure out why it's bugging on our side.

The bug is on all popover element, including TheNavbar menu

A quickfix which seems to work is to remove the `portal` prop in the `<Float>` element

**Comment by wa0x6e** [comment]
After some more testing, issue is coming from the headlessui/float library (https://github.com/ycs77/headlessui-float/issues/53). Let's proceed with a hotfix on our side, by temporary removing `focus` on the popoverPanel.
