### ISSUE TITLE
How do I get voting power

### ISSUE THREAD

**Issue by Bettyrockergit** [snapshot-labs/snapshot#4936]

**Comment by ChaituVR** [comment]
Please create a ticket with more details at https://help.snapshot.org/en/

**Comment by a-bonfim-tech** [comment]
This looks less like a technical bug and more like a governance UX / mental-model issue.

From a user perspective, it’s not always clear:
- whether the wallet is eligible to vote (voting power > 0),
- what exactly is being signed (off-chain message vs on-chain transaction),
- and at which point the action has an actual effect on governance.

That ambiguity creates friction and also increases security risk, since users may end up signing messages they don’t fully understand just to “try again”.

It might help to make the flow more explicit at each step, for example:
- clearly indicating voting eligibility before prompting any signature,
- explicitly stating that the action is an off-chain signature with governance intent,
- and separating identity verification from the voting action in the UI.

Happy to help draft concise acceptance criteria or documentation notes if this kind of clarification would be useful.
