### ISSUE TITLE
Create specs for browser notification service

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot#663]

**Comment by bonustrack** [comment]
@harshmaur We have already an event system on snapshot-hub that we could leverage to send notification, seemore details  here https://docs.snapshot.org/webhooks

**Comment by midgerate** [comment]
## Functional Specification

As a user 
- I should be able to subscribe to proposal notification for any space in snapshot. 
- I should be able to unsubscribe to notifications from any subscribed space. 
- Since I can also block notifications from the browser, I need to know if I need to allow notifications again to be able to receive the notifications. 
- I should be able to see all my subscribed spaces in one screen and I should be able to unsubscribe one by one or all at once. 

As a developer
- I need a simple solution that provides an SDK to allow users to enable push notifications in their browsers
- I need to be able to programatically send push notifications to all the subscribed users without having to run loops. 
- I need support from the SDK that allows me to manage subscription / unsubscription of the users without writing too much code. 
- I need a solution that ensures deliverability of the message to all the users subscribed. 
- I need a solution that is easy to integrate with vue.js

## Technical Specifications
TBD

**Comment by bonustrack** [comment]
@harshmaur We dont need to worry about "Slice 4". For now we just need the notification enabler button on space page.
I dont understand what PWA has to do with this feature? You can use workers with Vue.js, you don't need PWA for that.

**Comment by midgerate** [comment]
@bonustrack You're right about PWA, we dont need that. but usually most articles would mention PWA because push notifications are usually used by PWA. 

It is not necessary to do that in our case.
