### ISSUE TITLE
When logged with a Safe, we should only sign message not send them (cuz it require others multisig signer to confirm the signature first)

### ISSUE THREAD

**Issue by midgerate** [snapshot-labs/snapshot#707]

**Comment by samuveth** [comment]
I don't see a way we can handle this on the frontend, it seems like this is an issue for `snapshot.js`

Also I tried voting when connected to Safe via WalletConnect and it shows this
![image](https://user-images.githubusercontent.com/51686767/135447668-8adc3ff4-605a-454e-9c0c-8d20f594ad58.png)

I can't find any error in the console so I'm not sure what the issue is.
